package dipankardas011:openai@0.1.0;

interface llm {
    text-to-text: func();
    text-to-image: func();
}

world genai {
    export llm;
    import dipankardas011:httpclient/outgoing-http@0.1.0;
}
