package dipankardas011:openai@0.1.0;

interface llm {
    text-to-text: func();
    /*String returned is a the location where to look for the image*/
    text-to-image: func(prompt: string) -> string;
}

world genai {
    export llm;
    import dipankardas011:httpclient/outgoing-http@0.1.0;
}
