package dipankardas011:watttime@0.1.0;

interface watttime {
    record point-data {
        point-time: string,
        value: f32
    } 
    record metadata {
        data-point-period-seconds: s32,
        region: string,
        warnings: list<string>,
        signal-type: string,
        model: string,
        units: string,
        generated-at-period-seconds: s32,
        generated-at: string
    }
    record forecast {
        data: list<point-data>,
        meta: metadata
    }
    register: func(username: string, password: string, email: string) -> bool;
    get-token: func() -> option<string>;
    get-region: func(token: string, signal-type: string) -> option<string>;
    get-forecast: func(token: string, region: string, signal-type: string) -> option<forecast>;
}

world green {
    export watttime;
    import dipankardas011:httpclient/outgoing-http@0.1.0;
}
