package dipankardas011:githubapi@0.1.0;

interface releases {
    get-latest-release: func(org: string, proj: string) -> string;
    get-contributors: func(org: string, proj: string) -> string;
    get-stars: func(org: string, proj: string) -> u16;
}

world project {
    export releases;
    import dipankardas011:httpclient/outgoing-http@0.1.0;
}
