package dipankardas011:githubapiv2@0.1.0;

interface releases {
    fetch-latest: func(org: string, proj: string) -> string;
}

world project {
    export releases;
    import dipankardas011:httpclient/outgoing-http@0.1.0;
}
